### ISSUE TITLE
Too large dataset for plotResiduals ?

### ISSUE THREAD

**Issue by FBdata** [florianhartig/DHARMa#130]
Hi, 

First, thank you for such a useful package. 

I am trying to analyze residuals for a binomial GLM : 
`fittedModel <- glm(formula, family = "binomial", data = train, weights = impressions)`

Here are characteristics of my train dataset : 
- number of rows : 91032
- features : 
-> variable 1 : categorical (6 levels)
-> variable 2 : categorical (7 levels)
-> variable 3 : categorical (3 levels)
-> variable 4 : categorical (2 levels)
-> variable 5 : categorical (3 levels)
-> variable 6 : numeric
-> variable 7 : numeric
- target feature : numeric between 0 and 1. 
```
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
0.000000 0.000000 0.000000 0.009818 0.004133 1.000000 
```

As described in your vignette, I use the simulateResiduals function and then want to plot QQplot residuals and Residual vs predicted plot. 
`sim<-simulateResiduals(fittedModel)`
`plot(sim)`
![dharma_plot](https://user-images.githubusercontent.com/16881728/69798384-79f29700-11d1-11ea-8f5f-e210487149ad.png)

But the predicted vs standardized residual plot is unreadable because of the too large dataset. I don't know how I can deal with this. 
- I was thinking about the recalculateResiduals function you describe in the vignette to group according to some variables. But I don't know if it is interesting to do it just to obtain better data viz. 
- Can I follow my residuals diagnostic without this residuals plot ? Just with some tests and QQplot ?

Thank you for any help!

**Comment by florianhartig** [comment]
Hi FBdata,

yes, the current res ~ pred plot is not ideal for a large number of data points. However, you can access the residuals via sim$scaledResiduals, so you can create any visualisation you want. 

As an example, I have just added an option to switch to a smooth scatter plot https://stat.ethz.ch/R-manual/R-devel/library/graphics/html/smoothScatter.html in the plotResidual function, this will create a plot like this one which is more suitable for very large datasets

![image](https://user-images.githubusercontent.com/5457753/70261428-b7878f00-1792-11ea-851a-e1f0be8f884e.png)

This will be pushed with the next CRAN update. If you want to use it immediately, use install the development version of DHARMa from GitHub (instructions see https://github.com/florianhartig/DHARMa)

About your other questions: 

- In general, all diagnostics of DHARMa can be used identically with large datasets as well. The only issues may be that, with a very large dataset, it is very likely that tests will be significant. In doubt, I would try to interpret things visually, rather than via p-values

- Regardless of the issue with seeing the patterns in the plot: for binomial GLMs with 0/1 response, it is very advisable to group residuals to check for overdispersion if you are interested in a statistical / causal analysis. The reason is that overdispersion doesn't show up unless you group the residuals. There are comments about this in the vignette. If you are only interested in prediction, i.e. if you use this as machine learning exercise, you can probably forget about this. Of course, this only works if you have a sensible grouping factor (spatial blocks are usually a good option).

Best,
Florian

**Comment by florianhartig** [comment]
OK,  this is now in the master, will be rolled out with the next CRAN release. I'll consider that closed.
