### ISSUE TITLE
glmmTMB fitted dispersion and DHARMa dispersionTest not in agreement

### ISSUE THREAD

**Issue by amynang** [florianhartig/DHARMa#143]
Hello,

My model summary gives me:
`Overdispersion parameter for beta family (): 7.03 `
and when I run the testDispersion() function on the simulation output I get 
`data:  simulationOutput
ratioObsSim = 0.95938, p-value = 0.024
alternative hypothesis: two.sided`
and
![image](https://user-images.githubusercontent.com/61004068/74718183-fbd2e900-5231-11ea-911c-7a86689c2dd1.png)
which if I understand correctly show significant underdispersion. 
What could be the reason for this disagreement?

this is my model: 
`m <- glmmTMB(Activity ~  ar1(as.factor(period) + 0 | layer:(sample:(RE1:(RE2:RE3)))) + 
                           Treatment1*scale(Treatment2)*layer + 
                           Before.After + scale(Treatment2):Before.After +
                           (1|RE3/RE2/RE1/sample),
                           ziformula= ~1,
              data=data,
              na.action = na.omit,
              family=beta_family())
`
Thanks,
Angelos

**Comment by florianhartig** [comment]
Hi Angelos,

first thing: DHARMa compares the fitted model against the data. In your case, glmmTMB fits a dispersion parameter of 7, which tells you (very broadly speaking) that there is overdispersion compared the the default value of 1, but for DHARMa, the reference is now the fitted model with 7, so if this fitted model with 7 is perfect, DHARMa should get a dispersion ration (Obs/Sim) of 1. Makes sense?

In your case, DHARMa tells you that the data seems to be slightly less variance than what one would expect with a beta glm with dispersion parameter 7. In my experience, this usually happens because either the dispersion, or the zero-inflation is not properly modelled. Plot your residuals against predictors, and have a look of dispersion or zero-inflation depends on the predictors (btw, you could also have 1-inflation, I would check for this too), and include this in your glmmTMB model. 

It should be noted though that the deviation is minimal (5%, this is nothing). It is probably only significant because you have a lot of data. If you can't find a obvious culprit, it is probably also OK to leave the model like it is. No model is perfect. 

btw: I hope you use the newest version of DHARMa? There was an update that improves the compatibility with glmmTMB.

Best,
Florian

**Comment by amynang** [comment]
Thanks you, that does make sense.

Following your suggestions I have plotted the residuals against the predictors.
![image](https://user-images.githubusercontent.com/61004068/74738587-867a0f00-5257-11ea-9497-4aaccd604e14.png)

I then added each of the predictors in the dispersion formula. (Not sure if this would make sense for interactions as well).
In the model summary, for the dispersion model with Treatment1, only the intercept was significant.
For the other three cases, both predictor and intercept were significant in the dispersion model. 
I followed that by adding all these three so 
`dispformula = ~ Before.After + layer + scale(Treatment2)`
and again, intercept and all predictors were significant. All these changes has lowered AIC values a lot. 

Other model diagnostics were not affected and fitted dispersion values remained significantly lower than predicted (although p values increased somewhat).
On the other hand, none of that changed the conditional model much, so any inferences made by that remain the same.

**Comment by florianhartig** [comment]
Hi Angelos,

OK, thanks for the feedback. I still think the slightly lower dispersion points to some kind of issue, but It's sometimes hard to say what the issue is. You could try again doing the same thing you did with the dispersion with the ziformula. It might also be that the beta is not a perfect fit for the distribution of your data.

In general, however, I don't think this is a big issue. As I said, the difference in dispersion is minimal.
