### ISSUE TITLE
Problems with installing DHARMa

### ISSUE THREAD

**Issue by larahurban** [florianhartig/DHARMa#153]
Hi Florian, 

I have now tried installing DHARMa in many different ways. 

When installing it from github (no matter which version) I get this error: 
Error: Failed to install 'DHARMa' from GitHub:
  (converted from warning) unable to access index for repository https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.5:
  cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.5/PACKAGES'

I was therefore wondering if there was a problem with the repository? 

Many thanks for letting me know. 

Best regards,
Lara

**Comment by florianhartig** [comment]
Hi Lara,

OK, you are talking about the development version, right? Because the CRAN version should install without problem. 

In the development version (on GitHub), there was indeed a bug, which I have fixed. Now it installs (at least for me).

Thanks for letting me know, I somehow pushed a change that didn't work, and the got distracted by the entire Corona thing. 

Cheers,
Florian

**Comment by larahurban** [comment]
Hi Florian, 

Great, thanks for the quick reply. Yes, all good now. 

Best wishes,
Lara
