### ISSUE TITLE
glmmTMB binomial models specified with proportion weights 

### ISSUE THREAD

**Issue by mebrooks** [florianhartig/DHARMa#158]
This is related to [a glmmTMB issue](https://github.com/glmmTMB/glmmTMB/issues/313), but it got lost in the details 2 years ago, so I thought it needed its own thread. I'm running a lot of binomial models where we specify the model in terms of proportions and weights instead of successes and failures. I think the simulations from glmmTMB are not getting rearranged by DHARMa (see my tests below, especially `testDispersion(restmb2)`). It would be nice to fix this either on the DHARMa side or the glmmTMB side of things, but there was already [a long discussion about this with respect to glmmTMB ](https://github.com/glmmTMB/glmmTMB/issues/259). The diagnostics should at least give an error, rather than false positives in tests.

```
library(glmmTMB)
library(DHARMa)
library(lme4) # for data
tmb1 = glmmTMB(cbind(incidence, size - incidence) ~ period + (1 | herd),
		data = cbpp, family = binomial)
cbpp2 = transform(cbpp, prop=incidence/size)

tmb2 = glmmTMB(prop ~ period + (1 | herd),
		data = cbpp2, weights = size, family = binomial)

all.equal(fixef(tmb1), fixef(tmb2)) #TRUE
all.equal(ranef(tmb1), ranef(tmb2)) #TRUE
all.equal(summary(tmb1), summary(tmb2)) #all except "call"

restmb1 = simulateResiduals(tmb1, n = 1000, seed=111)
restmb2 = simulateResiduals(tmb2, n = 1000, seed=111)

all.equal(testUniformity(restmb1), testUniformity(restmb2)) #big differences
testDispersion(restmb1) #OK
testDispersion(restmb2) #BAD
```

**Comment by florianhartig** [comment]
Hi Mollie, thanks for reporting this - I realized that glmmTMB is handling the weights differently than lme4, but I had thought I had accounted for this, but apparently not. Will investigate.

**Comment by florianhartig** [comment]
Hi Mollie, I hope this is fixed now, many thanks for the pointer!

As a side comment, after going through all the tests and options again, I have to say that how the binomial weights implementations is handled by different packages is really a mess and very inconsistent between e.g. spaMM, glmmTMB and lme4. 

* lme4 - if fit with proportions + weights, will simulate proportions, and has to be refit with proportions
* glmmTMB - if fit with proportions + weights, will simulate integers, can be re-fit with integers or proportions (I think, doesn't really matter because I have a custom refit function)
* spaMM - weights in spaMM are only for adjusting the dispersion (seems to be identical to the dispersion parameter in glmmTMB), and thus cannot be used for the binomial 

In retrospect (but this is water down the bridge), I feel weights should have never been accepted to adjust the counts in the binomial, or the dispersion. Ideally, models would have 3 parameters

* dispersion (for families with a dispersion parameter, like in glmmTMB)
* weights (which should be a true weight on the likelihood), plus, if set, an warning should be raised that this is a pseudo-likelihood, meaning that one cannot simulate from this model (implemented in some packages, but not all, I think glmmTMB doesn't warn)
* and I'm not sure if the incidence parameterization is really needed at all, but if so, it should have received an extra argument.

Cheers,
Florian
