### ISSUE TITLE
Duplicate value and Error in if (all(values%%1 == 0)) for GLMM with Gamma distribution

### ISSUE THREAD

**Issue by IvaneNuel** [florianhartig/DHARMa#163]
Dear Florian Hartig,

I want to analyse reaction times based on to two categorical fixed factors and participants and stimuli as random factors (only the intercept). Due to the positive skewed distribution of RT I ran a glmm with a gamma distribution and an identity link function (Lo & Andrews, 2015).

Here is my model:

`Model_Mn_VAAST_gamma<- glmer(VAAST.RT~Conditionc* Type_Bloc_Encounteredc + (1|pp) + (1|Perso), Pilot5_FINAL_Mn2, 
                                 family = Gamma(link = "identity"),
                                                glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 100000)))
`

I would like to use the DHARMa package to investigate the residuals. 

`simulationOutputGamma <- simulateResiduals(fittedModel = Model_Mn_VAAST_gamma, n = 250)
`

But I have the following message that I don't understand.

`Model family was recognized or set as continuous, but duplicate values were detected in the response. Consider if you are fitting an appropriate model.
Error in if (all(values%%1 == 0)) { : 
  missing value where TRUE/FALSE needed
In addition: Warning message:
In rgamma(nsim * length(ftd), shape = shape, rate = shape/ftd) :
  NAs produced`

I apologise if this is a dumb question ...

Thanks in advance for any information.

Ivane

**Comment by florianhartig** [comment]
Hi, I think the reason here is that you fit gamma with identity link. There are certain reasons to do this, but note that the identity link does not guarantee values are >0, which is required for the Gamma. 

I think this still works fine for the fitting, but then, when lme4 simulates, the REs produce negative values on the scale of the linear predictor, which produces NAs in the gamma, causing this problem. 

I don't think there's much I can do about this in DHARMa. For you, I guess it depends on whether you have chosen identity link with definite reasons, or just accidentally. If you have definite reasons, I think https://cran.r-project.org/web/packages/gjam/index.html has some extended support for truncation with identity links, and could maybe be supported by DHARMa, but isn't at the moment. Otherwise, I would suggest to use the standard canonical link for the Gamma

**Comment by IvaneNuel** [comment]
Thank you very much for your quick reply and your help!
I better understand the issue. I follow recomamndation from a previous paper about RT analyses but I will consider to change the link.
