### ISSUE TITLE
Coping with underdispersion after DHARMa diagnosis on GLMM with Gamma link=log

### ISSUE THREAD

**Issue by sarapalacio** [florianhartig/DHARMa#180]
Dear Florian

Thanks for creating DHARMa, I have been using it to detect issues in a GLMM model fit to a Gamma distribution with link=log funtion and it seems we have underdispersion issues. In your description of the package you mention some steps to take when dealing with overdispersion and provide a case example of an underdispersed model. However, I could not find any recommendations as to how to improve the performance in underdispersed models. Any help would be appreciated!

We have a model to test for the effects of affinity to gypsum soils (Gyps_type) and life form on the S concentrations of plants. We have 5 reps per species so we include the taxonomic family and the species (nested within family) as random terms to account for phylogenetic issues. Our data are foliar nutrient concentrations, hence compositional data. We considered transforming them using clr, but decided working on raw data whenever possible to make interpretation of results easier. Since residuals were not normally distributed and variance increased with means we chose a Gamma distribution. The AIC criterion showed link=log as the best function to use for our data. I paste the model below and the output we obtained from DHARMa. Hope this helps. Thanks in any case for your attention!

glm<-glmer(S~Gyps_type*Life_form+(1|Family)+(1|Family:Species), data=Nutr_gyp, family=Gamma(link="log"))

![imagen](https://user-images.githubusercontent.com/65897967/82805889-0b8f4880-9e85-11ea-9e9a-b6faa1a22efb.png)
$uniformity

	One-sample Kolmogorov-Smirnov test

data:  simulationOutput$scaledResiduals
D = 0.53866, p-value < 2.2e-16
alternative hypothesis: two-sided

$dispersion

	DHARMa nonparametric dispersion test via sd of residuals fitted vs. simulated

data:  simulationOutput
ratioObsSim = 0.060874, p-value < 2.2e-16
alternative hypothesis: two.sided

$outliers

	DHARMa outlier test based on exact binomial test

data:  simulationOutput
outLow = 0.0000e+00, outHigh = 0.0000e+00, nobs = 4.5600e+02, freqH0 = 3.9841e-03, p-value = 0.3239
alternative hypothesis: two.sided

![imagen](https://user-images.githubusercontent.com/65897967/82805988-35e10600-9e85-11ea-9ad5-ac0628c76ff0.png)

I tried plotting the residuals vs the fixed factors of the model. It all looks fine to me...

![imagen](https://user-images.githubusercontent.com/65897967/82806102-6aed5880-9e85-11ea-85fe-7ef313d6abaf.png)

fisrt plot residuals vs Gyps_type, second plot residuals vs Life_form

Cheers,

Sara

**Comment by florianhartig** [comment]
Hi Sara,

sorry for the late reply. With this kind of questions, it's hard to give general answers, but I will share a few ideas:

* About your comment with the log link: AIC can be a useful too to decide which of several plausible models is preferable. But the candidate models tested with AIC should all be plausible, i.e. fit to the the data. If they don't, their inference won't be reliable, including their AIC value. Thus, first search for models that are plausible given your data, and if you find several ones, you can select among them with AIC (with the usual caveats). 

* About plausible models - I would consider both gamma and OLS (with transformed responses) in your case. Gamma is definitely a good candidate for your problem, but I don't see why OLS (or even robust LS models) should not be considered. 

* My best guess about what's happening in your case is that the residual distribution doesn't fit very well to a gamma distribution. I suspect that you have fatter tails (= outliers) than one would expect in a gamma. In this case, the gamma will adjust it's parameters towards wider dispersion, to explain the outliers, which means that you have a wider dispersion than would be needed for the rest of your data, causing DHARMa to show underdispersion. Possible solutions for this might be

  * Try OLS or robust regression with a suitable transformation instead of the gamma
  * Consider if you can add predictors or if you fit the right functional form
  * Try gamma with variable dispersion via the package glmmTMB
  * Try (last resort, this is hacky) an observation-level RE in your gamma to modify the distribution 

Of course, also the standard advice applies: have a good look at your data, and see if there are data points that stand out, or if the properties somehow don't fit to a Gamma.

Feel free to post follow-up questions here. 

Best,
Florian

**Comment by sarapalacio** [comment]
Dear Florian,

Thanks so much for your useful response! You got the issues with our data perfectly right. We are dealing with foliar S concentrations in plants from atypical soils rich in S, some soil speciallists accumulate almost one order or magnitude higher S, so that probably explains the flatter tail. These high values, however, are not outliers, so we cannot remove them. We tried different transformations but none of them worked for our data, so in the end we tried glmmTMB, and it worked quite well! There are still some small issues, but I copy paste DHARMa output below, you can see they really improved as compared to models built with lmer.

Family: Gamma  ( log )
Formula:          S ~ Gyps_type * Life_form + yeso + (1 | Family) + (1 | Family:Species)
Data: Nutr_gyp

![imagen](https://user-images.githubusercontent.com/65897967/84522058-3cb9a680-acd6-11ea-958a-1839abfa415c.png)
![imagen](https://user-images.githubusercontent.com/65897967/84522091-4b07c280-acd6-11ea-9b3a-ad8163d4aa89.png)

$uniformity

	One-sample Kolmogorov-Smirnov test

data:  simulationOutput$scaledResiduals
D = 0.081203, p-value = 0.00645
alternative hypothesis: two-sided


$dispersion

	DHARMa nonparametric dispersion test via sd of residuals fitted vs. simulated

data:  simulationOutput
ratioObsSim = 0.96375, p-value = 0.88
alternative hypothesis: two.sided


$outliers

	DHARMa outlier test based on exact binomial test

data:  simulationOutput
outLow = 0.0000e+00, outHigh = 0.0000e+00, nobs = 4.3500e+02, freqH0 = 3.9841e-03, p-value = 0.3523
alternative hypothesis: two.sided

There are some deviation issues, but the models seem to behave much better and dispersion issues are solved.

THANKS FOR ALL YOUR HELP!

Best wishes,

Sara
