### ISSUE TITLE
DHARMa diagnostics show significant deviations in KS tests for a glmm with beta distribution

### ISSUE THREAD

**Issue by CelesteKieran** [florianhartig/DHARMa#181]
Hi Florian,

I'm a new user of DHARMa and recently posted this question on stack exchange. I saw a comment for a different user where you suggested to ask here instead, so here goes. Thanks for your time.

I'm trying to use glmmTMB to fit a beta-distributed generalized mixed effects model with nested random effects. DHARMa residual diagnostics show a KS test with significant deviation. Is this serious cause for concern? Does this signify I am using the wrong distribution and my models are invalid? 

.

I am attempting to show the relationship between salmon abundance and its fertilization effect on forests by means of satellite NDVI (greeness) measurement. An example of two of my models are:

glmm1 <- glmmTMB(grow_mean ~ combined_abundance_scaled + dist + slope + summer_mean_temp_scaled + summer_mean_precip_scaled + dist_head_scaled + sat + (1|block/plot.id), family=list (family="beta",link="logit"), data = fulldf)

glmm2 <- glmmTMB(grow_mean ~ pulse_year + dist + slope + summer_mean_temp_scaled + summer_mean_precip_scaled + dist_head_scaled + sat + (1|block/plot.id), family=list (family="beta",link="logit"), data = fulldf)

Where:

grow_mean = satellite NDVI measurements, ranging from 0.5085 - 0.8948

combined_abundance_scaled = scaled yearly abundance of salmon

pulse_year = a yes/no categorical variable that denotes whether the year had 'extreme' abundance

Other variables are: distance from riverbank (CLOSE/FAR), slope (Erosional/depositional/unknown), scaled mean temperature, scaled mean precipitation, scaled distance from headwaters, satellite (LANDSAT 5/LANDSAT 7/LANDSAT 8), and the random effects are plot.id (169 plots where yearly satellite data was collected) and block (2 associated plots, close and far, in each block).

data example

![Screen Shot 2020-05-27 at 8 19 11 AM](https://user-images.githubusercontent.com/61250454/83043695-0999c680-9ff8-11ea-8372-b12cde22d382.png)

When running the models I receive the warning messages:

Warning messages:

1: In glmmTMB(grow_mean ~ combined_abundance_scaled + dist + slope + : some components missing from ‘family’: downstream methods may fail

2: In mkTMBStruc(formula, ziformula, dispformula, combForm, mf, fr, : specifying ‘family’ as a plain list is deprecated

However, these same warning messages popped up in the glmmTMB vignette and didn't seem to be problematic, so I continued on.

simulationOutput <- simulateResiduals(fittedModel = glmm1, plot = T)

![Screen Shot 2020-05-27 at 8 29 27 AM](https://user-images.githubusercontent.com/61250454/83043794-27672b80-9ff8-11ea-827f-218b1ea57fb4.png)

simulationOutput <- simulateResiduals(fittedModel = glmm3, plot = T)

![Screen Shot 2020-05-27 at 8 30 08 AM](https://user-images.githubusercontent.com/61250454/83043808-2b934900-9ff8-11ea-941d-c66839475c3a.png)

How much of a problem is this? From my understanding strong deviations in the Kolmogorov-Smirnov test show a poor goodness of fit. Is the problem likely with my choice of beta-distribution, or do I need to transform my data in some way? I know there are some outliers in the data (below) but there are a lot of data points (5915 NDVI observations) that are quite mean centered.

Apologies if this question is over or under-explained, I'm fairly new to R coding and statistics. Thanks so much for any advice you could offer.

More diagnostics for glmm1 and a cullen and frey for the NDVI data:

![Screen Shot 2020-05-27 at 8 33 36 AM](https://user-images.githubusercontent.com/61250454/83043926-58476080-9ff8-11ea-95a2-299d6b7bb7fd.png)
![Screen Shot 2020-05-27 at 8 34 10 AM](https://user-images.githubusercontent.com/61250454/83043932-59788d80-9ff8-11ea-9ff0-9b61b9e39ab8.png)
![cullenandfrey(for NDVI points)](https://user-images.githubusercontent.com/61250454/83043938-5b425100-9ff8-11ea-82fc-fe20754d5186.png)

**Comment by florianhartig** [comment]
Hi Celeste,

about the glmmTMB warnings: I don't think this is an issue for what you are doing here, but if using family=beta_family() removes this warning (as suggested [in response to your SE question](https://stats.stackexchange.com/questions/468900/dharma-diagnostics-show-significant-deviations-in-ks-tests-for-a-glmm-with-beta)), I would use that instead of using "beta", just to be on the save side. If you have time, you can [file an issue at the glmmTMB github page](https://github.com/glmmTMB/glmmTMB/issues) to let the glmmTMB people know about the problem - I suspect it's mostly an issue of cleaning up the documentation / function interface on the glmmTMB side.

About your "misfit" - I don't think your results show a large misfit. Yes, the p-value shows you that there is a significant deviation from the assumed distribution, but significance != effect size. In other words, if you have a large number of data points (as you have here), even the slightest deviation will become significant. This is more or less what I think is going on here. If you look at the distributions, I see that 

- the qq-plot is nearly linear, suggesting that the overall distribution is roughly OK
_ the res ~ fitted looks approximately OK, maybe with a bit higher density towards the middle, and in particular a bit fewer larger values than expected. 

As suggested in SE, you could try with quantreg = T (will take some time) to get a bit better diagnostics on the res ~ fitted plot, and I would also recommend to plot residuals against all predictors. If that doesn't produce a clear pattern, I would say your model is acceptable.

Best,
Florian

**Comment by CelesteKieran** [comment]
Hi Florian,

The 'famiy=beta_family()" cleared up the warnings, and the residuals vs
predictor plots seem to support the model. I'm a bit new to statistics and
your diagnosis is comforting and greatly appreciated, thanks for your
patience.

Thank you and best wishes,

Celeste

**Comment by florianhartig** [comment]
Great, glad this was useful. I will close this!
