### ISSUE TITLE
DHARMa for model validation / selection

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/DHARMa#198]
Questions from a user:

> I'm a graduate student studying marine ecology, and I've been using your fantastic DHARMa package to validate GLMMs for my work. I was wondering if you've put any thought into how you might integrate DHARMa into a model validation and selection pipeline, and in particular, how (or if) you would think about test P values in the case where several models are considered. 
> 
> For example, the following script applies DHARMa tests to a list of models, similar to how AICcmodavg::aictab() works. P values returned from DHARMa tests are adjusted following the Benjamini and Hochberg method.  
> 
> ```
> validate <- function(mod_set, n = 1000){
>   # Do model validation
>   df <- do.call(rbind,
>                 (lapply(mod_set, loopdy, n = n)))
> 
>   mod_form <- df %>%
>     dplyr::select(response, predictors) %>%
>     dplyr::mutate(id = 1:length(mod_set))
>   ps <- df %>%
>     dplyr::select(-response, -predictors) %>%
>     dplyr::mutate(id = 1:length(mod_set)) %>%
>     tidyr::gather(Var, Value, -id) %>%
>     dplyr::mutate(Value = stats::p.adjust(Value, method = "BH")) %>%
>     tidyr::spread(Var, Value) %>%
>     dplyr::left_join(.,mod_form, by = "id") %>%
>     dplyr::select(-id)
>   return(ps)
> }
> 
> loopdy <- function(mod_set,n = n){
>   scaled_sims <- DHARMa::simulateResiduals(fittedModel = mod_set, n = n)
>   res_tests <- invisible(DHARMa::testResiduals(scaled_sims, plot = F))
>   zinf <- DHARMa::testZeroInflation(scaled_sims, plot = F)
> 
>   out <- data.frame(response = as.character(formula(mod_set))[2],
>                     predictors =  as.character(formula(mod_set))[3],
>                     uniformity_p = res_tests[[1]]$p.value,
>                     dispersion_p = res_tests[[2]]$p.value,
>                     outliers_p = res_tests[[3]]$p.value,
>                     zeroinf_p = zinf$p.value)
>   return(out)
> }
> 
> mod_list <- list()
> mod_list[[1]] <- glmmTMB(count ~ mined + (1|site), zi=~mined, family=poisson, data=Salamanders)
> mod_list[[2]] <- glmmTMB(count ~ mined + cover + (1|site), zi=~mined, family=poisson, data=Salamanders)
> mod_list[[3]] <- glmmTMB(count ~ mined + cover + spp + (1|site), zi=~mined, family=poisson, data=Salamanders)
> validate(mod_list)
> 
> ```
> Do you think this approach is valid? Interested to hear your thoughts.

**Comment by seanhardison1** [comment]
Thanks, Florian.

I should clarify that the procedure described in my email would be used prior to model selection, not as a form of model selection (i.e. instead of an IC based method). Models not meeting residual test thresholds would be identified for further investigation or left out of model selection using IC-based methods. My goal was to address step 3 in the model selection guidelines outlined in the [AICcmodavg](https://cran.r-project.org/web/packages/AICcmodavg/AICcmodavg.pdf) vignette:

> 3) Check model fit. Use your global model (most complex model) or subglobal models to determine
if the assumptions are valid. If none of your models fit the data well, information criteria will only
indicate the most parsimonious of the poor models. 

I believe that approach follows what you're suggesting in your summary statement, but please correct me if I'm misinterpreting. 

With respect to P values, I was specifically concerned about the possibility of test errors given multiple testing. Might be an interesting simulation experiment?

**Comment by florianhartig** [comment]
Hi Sean,

yes, if this is only an overview / pre-screening, this makes sense to me.

I would tend not to correct p-values for multiple testing, because I believe that nearly all tests are correlated anyway (if you have overdispersion, this will also trigger ks and outlier tests), so this is not really multiple testing, but rather a range of similar tests.

**Comment by seanhardison1** [comment]
Got it. Thanks so much! I appreciate your insight.

**Comment by florianhartig** [comment]
Maybe the function testResiduals could be modified to provide a table? At the moment, I don't think it adds much utility over the standard Plot, which already performs all these tests.

**Comment by seanhardison1** [comment]
I like the idea of giving users the option of returning a table with a model summary rather than having test results print to the console (maybe broom outputs?).

However, I think the the option to simulate from and test multiple models at once would provide the most value to users. In both cases, it would make sense to provide more contextual information than just P values.

**Comment by florianhartig** [comment]
ok, I see what you mean. Maybe one could implement something like summary(mod1, mod 2, mod3) ?

**Comment by seanhardison1** [comment]
Yep, something like that! I'm happy to contribute a non-tidy PR if you'd like.

**Comment by florianhartig** [comment]
sure, if you have time go ahead! I'll consider including this in the next release!

**Comment by florianhartig** [comment]
OK, will close this here and open a separate issue.

**Comment by florianhartig** [comment]
Issue is here https://github.com/florianhartig/DHARMa/issues/204
