### ISSUE TITLE
Error in plotResiduals on count data (using glmmTMB)

### ISSUE THREAD

**Issue by locoric** [florianhartig/DHARMa#269]
Hi all, 
I am using Dharma for the first time to diagnose my model on count data. 
My model looks something like this: 

`glmmTMB(count ~ pred1 + pred2 + pred3 + pred3:pred4 + pred2:pred4 + (1 | group), family = poisson(link = "log"), data = data)`

Then, I simulate the residuals through DHARMa: 

`simulateResiduals(mod, n = 1000, integerResponse = T)`

I can see that the model is underdispersed (RatioObsSim = 0.72). Fitting a `compois(link = "log")` regression with `dispformula =  pred1 + pred2 + pred3` correctly accounts for underdispersion (which now is 0.81 and not significant).
However, when I try to plot my residuals against specific predictors, the function 'plotResidual' outputs the following error: 

`Error in ensurePredictor(simulationOutput, form) : 
  DHARMa: residuals and predictor do not have the same length. The issue is possibly that you have NAs in your predictor that were removed during the model fit. Remove the NA values from your predictor.`

I would like to understand what is causing this problem. I have no NAs in my data. The predictor that I am using is numerical but used as factor. The only way I could find to plot the residuals against my predictor is to extract them and  create a new vector in my dataframe. At that point, the function works as predicted. I cannot understand whether this is a problem in my model, or whether it is a problem in the simulation of the residuals. 
Any help is greatly appreciated!

**Comment by florianhartig** [comment]
Hi @locoric, thanks for reporting this. Would you be able to share a reproducible example (with data)?

**Comment by locoric** [comment]
[data.txt](https://github.com/florianhartig/DHARMa/files/6195680/data.txt)

Here's the dput output of my data (transformed cause of privacy but maintaned the same distribution). 
And here's the code that generates the error: 

`mod <- glmmTMB(resp ~ as.factor(pred1) + pred2 + pred3 + pred2:pred4 + pred3:pred4 + (1|group), data = df,family = poisson(link = "log"))
  
mod_res <- simulateResiduals(N_Ants_mod, n = 1000, integerResponse = T)

plotResiduals(mod_res, form = "pred1")`

Thanks for your time!

**Comment by florianhartig** [comment]
Hi, sorry, I could have seen this directly - your issue here is that you provide your predictor as a string, but currently, you have to provide this as a variable. It's my long-term plan to support the string notation, as it seems logical for a user to expect this, but I haven't found the time to do the coding. So, for the moment, if you do 

`plotResiduals(mod_res, form = df$pred1) `

plots will work. The plot below is done with the new version (0.3.4) of DHARMa, which just went on CRAN yesterday, and includes improved plots / tests for categorical predictors. I would suggest to update to 0.3.4, because this will be helpful in your case.  

![image](https://user-images.githubusercontent.com/5457753/112291294-45d99a00-8c90-11eb-9306-28f8baff8370.png)

**Comment by locoric** [comment]
@florianhartig thanks for your help! I don't know why I assumed that the function required a string character, and now I just noticed that even on the help there is an example in which you use the df$pred1 notation, my bad! 
I think that the confusion may arise from the fact that the function returns `variable not found` if one does not use the quotation marks, but returns a different error when you use the character string. 

Thanks again! Cheers
