### ISSUE TITLE
Add hurricane dataset to DHARMa

### ISSUE THREAD

**Issue by florianhartig** [florianhartig/DHARMa#276]
Add the hurricane dataset to DHARMa, including this analysis https://theoreticalecology.wordpress.com/2021/04/17/hurricanes-and-himmicanes-revisited-with-dharma/ in the help.

See https://r-pkgs.org/data.html and other packages how to do this.

**Comment by EttnerAndreas** [comment]
I already added the dataset, with two new folders, and a help file.

- raw-data: which included the raw data, and in this example is changed and only specified until row 93, since afterwards follows text/description
- data: which contains the dataset, available for users
- ?hurricanes : opens up a help file, where i tried to add detailed explanations as well as example code you reccommended. 

When loading the package, dataset is available.
