### ISSUE TITLE
Can a model with significant quantile deviation be used for making inferences?

### ISSUE THREAD

**Issue by IhsanKhaliq** [florianhartig/DHARMa#285]
Hi Florian,
I have a quick question regarding quantile deviations detected. Does that really matter if these are detected when I'm only interested in making inferences, and NOT predictions? I have a large time series data set (effect of environmental factors on the spatiotemporal development of a plant disease/number of infected plants) that's highly over dispersed due to excess zeros. But excess zeros explain an important ecological process and is not a nuisance or a sampling error. The KS test is also significant, but I am not worried about that because when I remove a log offset or one predictor (wind direction) it disappears. I don't want to remove wind direction predictor just to make KS test non-significant because it explains significant variability. There seems to be moderate positive correlation between two predictors (relative humidity and wind directions), but since both are not directly related, I have kept both of them. 

This is my model 

mod3 <-
   glmmTMB(
      infected_plants ~ total_rain + wind_direction + avg_rh * wind_direction +  avg_temp + distance + location + (1 | assessment_number) +  offset(log(total_plants)),
      family = nbinom1,
      data = dat
   )

Here is the residuals plot when both wind direction and relative humidity predictors are included

![Screen Shot 2021-05-30 at 3 55 20 pm](https://user-images.githubusercontent.com/54728693/120094502-1a799c80-c164-11eb-996c-b8caa3984896.png)

And here is the residuals plot when wind direction is removed. As you can see, the KS test become non-significant, but I am not sure I should remove an important predictor just to make KS test non-significant. Not sure about quantile deviations though. Thanks you!

![No-w-s](https://user-images.githubusercontent.com/54728693/120094521-37ae6b00-c164-11eb-9313-4cd30e441476.png)

**Comment by florianhartig** [comment]
This is hard to say. As discussed also here https://cran.r-project.org/web/packages/DHARMa/vignettes/DHARMa.html#general-remarks-on-interperting-residual-patterns-and-tests, significant DHARMa tests alert you that there COULD be a problem (as you do inference / predictions under assumptions that deviate from your data), but whether the pattern is really a problem for your inference is something that you would need to explore, by reason or simulation.

My persona guess in this case: yes, the right pattern could have an impact on inference / p-values - if you say you have a problem with excess zeros, why not use the zi term in glmmTMB?

**Comment by IhsanKhaliq** [comment]
Thanks for the quick response. As I understand, too many zeros don't mean zero inflation. Zero inflation means when you get more zeros than expected. In my case, many zeros explain an important ecological process, so I don't want to use zero inflation. I was expecting excess zeros. The inferences I'd make from the model seems logical and backed up by literature (so I have the reason to trust model), but I wasn't sure how much of a problem significant DHARMa tests are.

**Comment by Istalan** [comment]
Hi,
sorry for butting in. 

I don't really see how this could be caused by zero inflation. The most immediate issue seems to be that the observations, which should be very large, aren't. 

Assuming the underlying model to be essentially correct, this can have two easy causes and of course an infinite number of complex ones. 

Cause 1: The value is too small small, e.g. it is censored.
Cause 2: The prediction is too big, e.g. the explaining variables are too big( or small depending on the sign of the coefficient). This can happen with missing values  encoded as 999 or -999. I have seen that happen.

Here are examples from simulation:
```
require(DHARMa)

testData = createData(sampleSize = 2000, family = poisson(), overdispersion = 0, randomEffectVariance = 0, intercept = 2)
m1 <- glm(observedResponse ~ Environment1, 
          family = "poisson", data = testData)
# no issues
res <- simulateResiduals(m1, plot = T)

# censoring
testData2 <- testData
hist(testData$observedResponse)
# censored data
testData2$observedResponse[testData2$observedResponse > 15] <- 15
m2 <- glm(observedResponse ~ Environment1, 
          family = "poisson", data = testData2)
# similar rise and fall, dispersion wouldN#t show in a negbinom model
simulateResiduals(m2, plot = T)

# weird missing codes, very woobly result but it can make more sense in a complex model
testData3 <- testData
# 100 weird error codes, that are large, but not crazy large
testData3$Environment1[1:100] <- 2
m3 <- glm(observedResponse ~ Environment1, 
          family = "poisson", data = testData3)
# similiar rise and fall
simulateResiduals(m3, plot = T)
summary(m3)


```
![censored_y](https://user-images.githubusercontent.com/31847671/120104974-4b9fa000-c157-11eb-9ced-19237880a4f4.png)

![missing_code](https://user-images.githubusercontent.com/31847671/120104978-4d696380-c157-11eb-81e5-a787b7d73c43.png)

You should probably take a good look at the data for the top 10% - 20% of predictions. or maybe just look for outliers in general.

On a completely separate note: I think a valid model should try to reflect reality, so if you expect  zero-inflation to be important it should be a part of the model. Just my 2 cents as i know nothing about ecology.

**Comment by IhsanKhaliq** [comment]
Thanks, Istalan. I think the reason is somewhat similar to your cause-2. I had only small source of infection at the beginning of the season. The number of infected plants in quadrats were zero until the mid/late season. Towards the end of the season, all plants were infected due to the onset of rain (disease is spread by rain). In summary, I had a lot of zeros until the end of the season. I think this is the reason the qq-norm plot shows deviations towards the upper end. As suggested by Florian, I used simulation and the estimates are more or less the same except for relative humidity, which is a non-significant predictor.  

Here is my model output
![model_out](https://user-images.githubusercontent.com/54728693/120148880-3e081a00-c22c-11eb-889a-c72c24677d6f.png)

Here is the result of simulated output 

![Screen Shot 2021-05-31 at 4 11 28 pm](https://user-images.githubusercontent.com/54728693/120148924-50825380-c22c-11eb-9cdb-ae4401eaf563.png)

Any further comments on this?

**Comment by florianhartig** [comment]
Hi @IhsanKhaliq ,

a) no, too many zeros (i.e. more than expected) mean zero-inflation, and especially when this is due to an ecological process you should model it. The conditional model can be interpreted ecolologically. 

b) That being said, I agree with @Istalan that the pattern is probably not primarily created by this problem, although zi does sometimes create weird things also at the upper end of the spectrum, so it would be worth testing it out imo.

c) I don't understand how you used simulations above to be sure that your residual problem is inconsequential, but that's also not really my job, what we can tell you from the DHARMa side is that your model assumptions don't seen to match the data-generating process, what you make with this info is up to you, and as I said, there can be cases where this is no problem.

**Comment by IhsanKhaliq** [comment]
Thanks. I do not have zero inflation because I was expecting many zeros. I just run DHARMa formal test for zero inflation. The value is almost 1 and p value is non-significant. The model actually fails to converge to when I try to use zero inflation. Regarding simulation, I was just checking if get similar estimates when I use simulation

![zi](https://user-images.githubusercontent.com/54728693/120184357-3bb9b600-c254-11eb-9b57-e79438e8522d.png)

As I indicated earlier, I get a much better quantile deviation plot when I remove the predictor wind direction. It has a moderate positive correlation (0.5) with relative humidity, but since both are different, I have kept both wind direction and relative humidity. Here is the plot residual plot without wind direction predictor. 
![Screen Shot 2021-05-31 at 9 21 00 pm](https://user-images.githubusercontent.com/54728693/120186003-407f6980-c256-11eb-83e4-3f54ebc270c5.png)

I'd love some comments on the above residual plot (without wind direction predictor)

**Comment by florianhartig** [comment]
Hi @IhsanKhaliq - the residual plot is still significant and the biggest effect is at the high values, as @Istalan said.

About removing wind: usually, this it's not sensible to remove predictors to improve residual plots. Plots may get marginally better, but a predictor is never the problem, as the model is free to switch it off (by estimating the respective value to zero).

**Comment by IhsanKhaliq** [comment]
Thanks Florian. I agree.
