### ISSUE TITLE
glmmTMB Beta regression with weights

### ISSUE THREAD

**Issue by mrml500** [florianhartig/DHARMa#293]
Hello - thanks for creating this package.

I have a dataset where I measured the amount of time males spent in courtship with females of their own species (conspecifics) or other species (heterospecifics) over multiple 5 minute time intervals. I am interested in the proportion of time that males spent courting conspecifics relative to heterospecifics, so my response variable (**prop_con**) is a continuous proportion of time spent courting conspecifics / total time spent courting. 

**male_species** is the only fixed factor and  individual male **id** a random factor.  

Because I have multiple cases where males only courted with conspecifics or only heterospecifics, I have both 0's and 1's in the response. To allow a fit using a beta distribution, I converted **prop_con**  to be within 0-1 using [this function](https://stackoverflow.com/a/36420932/4400333):

`y.transf.betareg <- function(y){
    n.obs <- sum(!is.na(y))
    (y * (n.obs - 1) + 0.5) / n.obs
}`

In addition, the amount of time that males spent courting (either conspecifics or heterospecifics) in each time period varied substantially, so I added a weights argument to the model call (**total_time_courting**), to give greater weight to observations where courtship was higher. 

This is my current model using glmmTMB:

```
model <- glmmTMB(prop_con ~  male_species + (1|id), weights = total_time_courting,
                 data = sympatric_con_het,
                 family = beta_family(link="logit"))

 Family: beta  ( logit )
Formula:          prop_con ~ male_species + (1 | id)
Data: sympatric_con_het
Weights: total_time_courting

     AIC      BIC   logLik deviance df.resid 
-12026.1 -12010.8   6018.0 -12036.1      152 

Random effects:

Conditional model:
 Groups Name        Variance Std.Dev.
 id     (Intercept) 0.4722   0.6872  
Number of obs: 157, groups:  id, 17

Overdispersion parameter for beta family (): 0.843 

Conditional model:
                Estimate Std. Error z value Pr(>|z|)  
(Intercept)       0.3769     0.3011   1.252   0.2106  
male_speciesALC  -0.8239     0.4376  -1.883   0.0597 .
male_speciesNDA   0.3760     0.4152   0.906   0.3652  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

```

Using DHARMa, I get the following warning about weights and resulting plots:

```
plot(simulateResiduals(fittedModel = model, n = 10000), rank = T)

7: In getSimulations.glmmTMB(fittedModel, nsim = n, type = "normal",  :
  Model was fit with prior weights. These will be ignored in the simulation. See ?getSimulations for details
```
![image](https://user-images.githubusercontent.com/49481251/125277812-d6a0b800-e309-11eb-85c8-6feb7f6687a8.png)

If I understand from the warning message and previous threads (https://github.com/florianhartig/DHARMa/issues/146 , https://github.com/florianhartig/DHARMa/issues/7), weights modelled using glmmTMB are ignored in DHARMa. But I was wondering if you had any advice on how I could go about evaluating this in other ways and whether the current model actually makes sense?

When I take the predicted probabilities of courting with conspecifics from the model output, the results are consistent with my expectations from looking at the data, but I'm not sure if the model itself is valid:

```
emmeans(model, ~ male_species, type = "response")

 male_species response     SE  df lower.CL upper.CL
 AALAT           0.593 0.0727 152    0.446    0.725
 ALC             0.390 0.0756 152    0.255    0.545
 NDA             0.680 0.0622 152    0.547    0.789

Confidence level used: 0.95 
Intervals are back-transformed from the logit scale 
```

**Comment by florianhartig** [comment]
Hi mrml500,

a few general comments first, unrelated to the weights:

- It seems your response variable consists of several observations combined? This seems weird, if you have several observations per individual, it would seem better to use a RE but keep each observation a single observation
- If you have many zeros / ones, you should probably consider zero/one inflated beta regressions

About the weights: 

- "weights modelled using glmmTMB are ignored in DHARMa." -> no, it's not DHARMa, they are ignored by glmmTMB when simulating, i.e. the problem is simulate.glmmTMB. The background is that if you set weights on the likelihood, as it is implemented in glmmTMB, there is no way to simulate from such a function - using weights creates a pseudo likelihood, so there is no explicit data-generating process associated with it.
- DHARMa checks: the problem with the weights in the described context is that if a data point gets low weights, it will likely be disregarded in the fit, and so it's residual may look bad. If the data is really coming from the model, and there is enough data to get a good fit, then residuals should still look good. However, if there is few data, models with weights can look bad. In your case, I would probably be concerned about the overdispersion, regardless of the weights, but it's hard to say without knowing your data better. 

In general, I think it can be debated if weights are an ideal way to solve your modelling problem. Recall above: weights create a pseudo-likelihood, so if you are using weights, you are never really modelling a data-generating process. I would recommend to think about how the data was generated, and whether it is possible to model this process statistically. So, for example, you could think about modelling:

* probability to interact in an encounter ~ het/con + other (logistic)
* time spent in an interaction ~ het/con (Gamma)

Which would both circumvent the necessity to put weighs and would much more directly model what you observe.
