### ISSUE TITLE
How to interpret / resolve residual pattern in negative binomial model

### ISSUE THREAD

**Issue by sjacobson1112** [florianhartig/DHARMa#304]
Hi Florian,
I am evaluating the fit of a negative binomial glm with 1000 observations and see that the KS test is significant but from reading through some other issues you've addressed it seems as though this sometimes happens with larger sample sizes and is not a major concern. However I'm worried about the pattern in the residuals that you can see in the attached figure. Do you think this indicates a poor model fit and do you have any suggestions of how I should proceed?

Details about the analysis:
I am looking at counts of alert behavior in elephants and a number of associated independent variables described below. A negative binomial model appeared to fit better than a poisson due to overdispersion. I have also thought about using a zero inflated negative binomial and am looking into how that will compare but would like to know if I can interpret results from the regular negative binomial as well.  
Here is the model: 
glm.nb(formula = TotalAlert ~ Location + daynight + PropFullMoon + scale(GroupSize) + SexRatio + scale(PropAdult) + offset(log(TotalEles)), data = grouplevel2, init.theta = 2.132411581, link = log)

Each observation may have a different number of elephants in view, so I've included an offset of the log(Number of elephants) to account for that. The predictor variables are location (categorical, OPA(outside protected area), PA(inside protected area)), time of day= daynight(categorical, day or night), proportion of moon visible= PropFullMoon (proportion 0-1), group size (continuous), and sex ratio (categorical, FEMALE=females>males, MALE= males>females, equal).

![image](https://user-images.githubusercontent.com/42970715/129225427-22b94180-24ba-4c0c-98bd-f36fbdd9396d.png)
Please let me know if other details would be helpful. Any advice would be greatly appreciated!
Sarah

**Comment by Istalan** [comment]
Hi Sarah,

not Florian here, but i've seen a similar issue before: #285 

Now your case seems simpler as you clearly have a cluster in the bottom right of your residuals vs predicted -plot. Now those are oberservations where the observed value (TotalAlert) is way smaller then what the model says they should be. Matter of factly the model predicts them to be the biggest. This has the knock on effect that the model underestimates the lower 80% of predictions, so that  those top 10% don't get overestimated even worse. 

Too get a better idea of what is going on i'd run something like this:
```
library(DHARMa)
library(mgcv)
library(MASS)
# setting up with fake data
testData = createData(sampleSize = 1000, fixedEffects = c(2, 1),
                      intercept = 2, # removes zeros at the left edge 
                      randomEffectVariance = 0, 
                      family = negbin(theta = 2, link = "log"),
                      numGroups = 200)

m <- glm.nb(observedResponse ~ Environment1 + offset(Environment2), data = testData, init.theta = 2, link = log)
# this model fits perfectly
res <- simulateResiduals(m, plot = T)

# first look at predictors as they actually are, not ranked or transformed
plotResiduals(res, form = predict(m, type = "response"), rank = F)

# just saving for future use
pred <-  predict(m, type = "response")
# logical index top 10% predicted observations 
index <- pred > quantile(pred, 0.9)

# predictors vs data
plot(pred, testData$observedResponse)
abline(0, 1)
#"zoomed" in
plot(pred[index], testData$observedResponse[index])
abline(0, 1)

#actullay looking at the data in the bottom right
testData[index & (res$scaledResiduals < 0.1), ]
```

**Comment by sjacobson1112** [comment]
Thank you @Istalan ! I'm attached the graphs from this closer look at the data, but I'm still not really sure what the solution is.. From reading the other, similar issue you mentioned, it seems like I should look for outliers or errors in that top percent of the data but I'm not sure how to determine the outliers. The outcome variable isn't that different in the top 10%, but there are a few observations with large numbers of elephants that have 0 as the outcome. The number of elephants is my offset variable so perhaps that would contribute the most to outliers in the dataset and I should remove those points with >170 in the top 10%? *I did try this for the two points you see in the data below and nothing changed.*
![residualvspred](https://user-images.githubusercontent.com/42970715/129249832-09195df2-0969-498b-be67-593f4a6aab82.jpeg)
![predvsdata](https://user-images.githubusercontent.com/42970715/129249846-e8605576-eb4f-402e-9410-8a841f61d9a8.jpeg)
![zoomplot](https://user-images.githubusercontent.com/42970715/129249863-574ba37c-a5b8-4534-8489-831e19a78779.jpeg)
<img width="1168" alt="Screen Shot 2021-08-12 at 2 23 21 PM" src="https://user-images.githubusercontent.com/42970715/129250777-f496212e-15c5-455b-ae7d-2eabe8bac5c0.png">


I did try looking at the data using zero inflation and the resulting residual graphs had more issues with fit than the negative binomial as well as the same quantile deviation at the high values (although not as extreme). 
A vuong test does indicate that the zinb model is better than the negative binomial, so as a novice in count regression, I'm not sure what to do.
Similar to the question asked in the other issue #285 I'm more interested in inference than predictions, so I wonder if my inference about which variables are associated with alert behavior are greatly affected by this strange fit in the negative binomial, or if there could be a statement I could include about when the relationships may not be as reliable based on the model. Hopefully that makes some sense! I'm also happy to provide more info if that's helpful.

**Comment by Istalan** [comment]
Ok,

small thing first: you're second plot isn't right, but it doesn't matter. 

I also don't see a real trend in the relevant data, but based on the graphs i'd say that you have 5 or 6 outliers. 5/6 values past predictor 10 are way smaller than they should be and the one 0 just before 10 could also be seen as weird. Now with theta of 2.1 almost nothing is truly an outlier, because  the variance is mu + (mu^2/theta) so small theta -> huge variance relative to mu, but those values visually don't fit and are probably driving the estimate of theta itself.  

Anyway take good look at those 6 and i'd fit a model without them, see what the new model would predict for them (see the docu of `predict.glm`, namely the `newdata` argument) and then you would have a presumably good model that breaks down pretty badly beyond a certain point. 

Other more or less desperate ideas would be to use link = "identity" or a logistic model on the percentage in each group that showed alertness. Not sure how the offset works in identity and whether  a logistic model makes sense or helps is a question i can't really answer. 

Also a disclaimer: I am way more of a random guy on the internet then an accomplished scientist, so external validation is recommend. Furthermore i'm going to bed. I hope this was helpful.

**Comment by sjacobson1112** [comment]
Hi @Istalan thanks again, I just realized that the graph I included of the indexed data above is not correct. I had accidentally used the fake data there. When I plot it with the real data it looks similar to the second plot that you said isn't right, I've attached both below. I'm not sure what I'm doing incorrectly there. I've included my R code adapted from your fake data example below.. any advice on what I may have done wrong?
Appreciate your input!

m <- glm.nb(TotalAlert~Location+daynight+scale(PropFullMoon)+scale(GroupSize)+
SexRatioN+scale(PropAdult)+offset(log(TotalEles)), data = grouplevel2, link = log)
res <- simulateResiduals(m, plot = T)

# first look at predictors as they actually are, not ranked or transformed
plotResiduals(res, form = predict(m, type = "response"), rank = F)

# just saving for future use
pred <-  predict(m, type = "response")
# logical index top 10% predicted observations 
index <- pred > quantile(pred, 0.9)

# predictors vs data
plot(pred, grouplevel2$TotalAlert)
abline(0, 1)
#"zoomed" in
plot(pred[index], grouplevel2$TotalAlert[index])
abline(0, 1)

#actually looking at the data in the bottom right
grouplevel2[index & (res$scaledResiduals < 0.1), ]

Two plots that don't look right..
![image](https://user-images.githubusercontent.com/42970715/129752598-f8a41234-6f81-4eee-ba48-b9c6fd4830a4.png)


![image](https://user-images.githubusercontent.com/42970715/129752526-7f042c1b-bdee-4883-86d8-c4253fd2bbc9.png)

**Comment by florianhartig** [comment]
Hi Sarah,

not so much to add here except what has already been established, i.e. that the main pattern is an overestimation of the model for large values, for which you have only a few data points, which likely results from a saturating response of one or several of your predictors. 

I would try if adding nonlinear terms (e.g. use sqrt pred or pred^2) solves the issue. The most likely culprit is your predictor with the most right-skewed distribution.

Cheers,
F

**Comment by sjacobson1112** [comment]
Hi Florian, 
Thank you for your response! I'm a bit confused about the overestimation, the model is overestimating my outcome variable but for large values of which predictor? This is what I'm struggling to understand and how that may relate to any decision to remove particular data points. When I looked at some of the data points that were overestimated using the indexing suggested above, it does seem like some of them have high values for my offset variable. But this wasn't a consistent pattern in the data so I'm not sure if that means I should remove all observations with very high values for the offset. I did try this for the most extreme values, but that did not remove the residual pattern.
Or do you think it is legitimate to present the inferences about relationships between variables from this model with the caveat that the model overestimates the outcome for high values? Again, here I think I really need to understand what the high values are of. My apologies if this is a more basic-level concept that I'm missing. 
I also tried adding the square and square root terms for the continuous predictors which didn't fix the issue either. Thanks again for your advice, it is greatly appreciated!
Sarah

**Comment by florianhartig** [comment]
Hi Sarah,

OK, the fact is that if you look at your very first plot, right panel, you see that for values where model predictions are highest, the model is overestimating, as all residuals are close to zero. The question is what can explain such a pattern.

1. Given that you have only linear responses specified, I deduced that you likely have a saturating response, i.e. for large values of one or several of your continuous predictors, the response saturates. You can explore this by plotting residuals against predictor, and try transformations of the predictors, e.g. sqrt(pred) or log(pred). It sounds as if you have done a bit of work in this direction already, without success, but I still think that this is the most likely culprit. Given the simple structure of your model, you could also try a gam, which takes care of the functional form automatically. Note that It is also possible that the pattern is caused by an interaction between continuous and/or categorical predictors, so you might want to explore this as well. 

2. Alternatively, the offset could of course also be a problem. If you want to check for this, you could use log(TotalEles) as a predictor instead of as offset, and of course this term could also be nonlinear, so you could consider transformations or splines.

3. Finally, note that besides the overestimation to high values, there also seems to be a bit of inhomogeneity in the other (right) residual pattern, with residuals being particularly likely around 0.85. I would have an eye on that, but first it seems important to understand the reason for the dip, as the other pattern might also disappear once this is solved. 

Overall, I would say that it is unlikely that this pattern has a major influence on your results, but it is very noticeable, and it seems very likely to me that this is a problem in the regression formula that should be possible to address, so I would try to explore further along the lines that I suggested above until you find out what the problem is.

**Comment by sjacobson1112** [comment]
Thank you so much for these suggestions, I will work through these steps and see if I can get a better fit! 
Sarah
