### ISSUE TITLE
No Support for GLMMPQL from MASS package

### ISSUE THREAD

**Issue by DexterGlass** [florianhartig/DHARMa#346]
No Support for GLMMPQL from MASS package

**Comment by florianhartig** [comment]
**Perspective for this request:** its seems glmmPQL does not implement any options to simulate from a fitted model, thus it is unlikely that I would integrate it in DHARMa. See also discussion in https://stat.ethz.ch/pipermail/r-sig-mixed-models/2012q4/019303.html. 

**Interim solution** for users that want to use DHARMa with glmmTMB: take your fitted model, create a simulate function for this model structure yourself, and then use createDHARMa (see help), this will allow most options of the package to be run.

See further comments on support of new packages in https://github.com/florianhartig/DHARMa/wiki/Adding-new-R-packages-to-DHARMA . The vignette has some further comments / examples on creating custom simulation functions and reading them into DHARMa

-> because it is unlikely that this can be implemented, I will close this issue. Feel free to re-open if there is an option to simulate from glmmPQL models that I have overlooked.
