### ISSUE TITLE
DHARMa's temporal autocorrelation plot differs from acf plot

### ISSUE THREAD

**Issue by mlkirchner** [florianhartig/DHARMa#368]
Hi! 

Thank you so much for this package! I use it all the time! Recently, I was analyzing a temporally autocorrelated dataset with a linear mixed model with glmmTMB and noticed that when I included the first order autocorrelation term, the DHARMA `testTemporalAutocorrelation` plot didn't seem to change much from the model without the term. Meanwhile if I plot the residuals with `acf`, the plots do differ. Why would this be happening? Are the residuals calculated by `recalculateResiduals` not accounting for the autocorrelation term somehow? Or am I missing an argument somewhere? See below for example: 

First, the model without any correction for autocorrelation: 
```
# Model w/o autocorrelation term
mean_lmm <- glmmTMB(mean_day ~ stratum + 
                      (1|tree_code) + 
                      (1|id) + (1|date),
                     data = tc_summ)

# DHARMA temporal autocorrelation results
simulationOutput <- simulateResiduals(fittedModel = mean_lmm) 
# Test for temporal autocorrelation
residrecal <- recalculateResiduals(simulationOutput, group = tc_summ$date)
testTemporalAutocorrelation(simulationOutput = residrecal, time = unique(tc_summ$date))
```

![image](https://user-images.githubusercontent.com/123994583/215592351-1053f6f4-14ba-4fda-ba5c-28330934c4a9.png)

The results clearly show that the residuals are autocorrelated and agree with the results of `acf`.

```
# acf temporal autocorrelation results
acf(residuals(mean_lmm)) 
```

![image](https://user-images.githubusercontent.com/123994583/215590741-397d2c4e-d5a3-4f08-970e-93d6daa5e09c.png)

Now, the model that includes a first-order autocorrelation term: 

```
# Model w/ AR1 term 
mean_lmm_ac <- glmmTMB(mean_day ~ stratum  + 
                         (1|tree_code)  + 
                         (1 | id) + (1 | date) + 
                         ar1(date + 0 | id), # First order autocorrelation 
                       data = tc_summ)

# DHARMA temporal autocorrelation results 
simulationOutput <- simulateResiduals(fittedModel = mean_lmm_ac) 
# Test for temporal autocorrelation
residrecal <- recalculateResiduals(simulationOutput, group = tc_summ$date)
testTemporalAutocorrelation(simulationOutput = residrecal, time = unique(tc_summ$date))
```

![image](https://user-images.githubusercontent.com/123994583/215591471-5fde9b6d-7c1a-43b1-ad23-59df29f40216.png)

These results are nearly the same as the model without the AR1 term, and differ from the results of `acf`. 

```
acf(residuals(mean_lmm_ac))

```

![image](https://user-images.githubusercontent.com/123994583/215591666-052061d4-b6b2-4024-9e6d-f3e21e81a03c.png)

The models differ in their summaries, estimates, and other DHARMA diagnostic plots, so it's not that the models are the same, but I can't figure out why DHARMA results are differing from `acf`. I know that with `lme` models, if you don't specify the `residuals(mod, type = "normalized")`, the call to `acf` won't take an autocorrelation term into account. Is something similar happening here? 

Thanks again! 
Michelle

**Comment by florianhartig** [comment]
Hello,

this is expected (however, admittedly, not ideal behaviour). The reason behind this is the following:

- DHARMa residuals are not expected to change because glmmTMB does not (yet) allow to condition simulations and predictions on the fitted REs, which encode your AR1 structure, so basically DHARMa residuals are calculated around your fixed effect structure (though they re-simulate the REs). See https://github.com/florianhartig/DHARMa/issues/16 and just opened issue https://github.com/glmmTMB/glmmTMB/issues/888. 

- Btw., note that many R packages such as gls have the same behaviour. It is a kind of special behaviour of glmmTMB that the AR1 REs are explicitly estimated and thus it is possible to condition on them. 
 
- Anyway, it seems that glmmTMB residuals are calculated conditional on fitted REs, so in this case you see the residual correlation minus the AR1 structure. 

How to fix this: 

- in DHARMa, you can currently either ignore the autocorrelation, or use the rotation argument, see https://github.com/florianhartig/DHARMa/issues/364

- I hope that the glmmTMB developers will include an option to condition simulations on the fitted REs in the future, which should produce similar residuals as you produce with act(residuals(model)).

**Comment by mlkirchner** [comment]
Hi Florian, 

Thanks for the quick and helpful response! I didn't realize that the DHARMa residuals for glmmTMB are not conditioned on the RE structure, but then it makes complete sense that the autocorrelation would still be present. 

I'm fine with ignoring the autocorrelation in DHARMa until [glmmTMB #888](https://github.com/glmmTMB/glmmTMB/issues/888) is addressed. 

But I did try the rotation argument and am still not getting the same results as `acf`. That's also to be expected, right? Because as you said in #301, "The problem, however, is that this will likely only work perfectly for symmetric linear homogenous cdfc, such as the multivariate normal." So, hypothetically, since I'm seeing a decrease in the autocorrelation structure  by including the rotation argument, that's indicative that the AR1 structure is effective, even though the autocorrelation isn't completely solved by DHARMa's calculations? 

This is mostly out of curiosity at this point, because as I said, I'm fine with continuing to use glmmTMB's residuals and `acf` to detect autocorrelation structure. 

Thanks again! 
Michelle

**Comment by mlkirchner** [comment]
Hi Florian,

Sorry for being uninitiated, but what do you mean by acdf? I'm not familiar
with that term.

I suspect you're correct that the random intercept of date is absorbing
some of the autocorrelation and causing the differences between the two.

I really appreciate your help on this!

Michelle

**Comment by florianhartig** [comment]
typo, I meant acf

**Comment by florianhartig** [comment]
OK, I will consider this closed for the moment, in case you have further questions feel free to re-open the issue!
