### ISSUE TITLE
Im getting significant deviations in KS tests for a glmm with guassian distribution 

### ISSUE THREAD

**Issue by ReneeAWB** [florianhartig/DHARMa#397]
Hello!
Im new to using R and im having trouble with a few things. I am working on finding out whether age and sex affects the weight of sheep. I am using the guassian disrtibution and when i use DHARMa, the KS test shows this warning. Im not sure if this is a significant issue or not, and im having trouble trying to find ways to fix it. 

<img width="766" alt="Screenshot 2023-12-19 at 22 54 30" src="https://github.com/florianhartig/DHARMa/assets/154384445/03f7f584-f2ff-4f81-a05b-157acab1d467">

**Comment by florianhartig** [comment]
Hi,

please see remarks in https://cran.r-project.org/web/packages/DHARMa/vignettes/DHARMa.html#interpreting-residuals-and-recognizing-misspecification-problems , in particular point 3.

In your case, the KS test is significant, but there is obviously although significant NO substantial deviation from the assumptions in your plot (because the QQ line is practically straight).

Best
F
