### ISSUE TITLE
Residuals vs. Predicted (interpretation)

### ISSUE THREAD

**Issue by MatildeCorreia17** [florianhartig/DHARMa#435]
Hi,
I have a dataset with 25612 observations and I modeled the utilization area against some biological traits, with a glmmTMB using family= gamma(link="log"). When I was analyzing the residuals with DHARMa package, I obtained the following plots:

 
<img width="353" alt="Captura de ecrã 2024-09-20, às 16 45 11" src="https://github.com/user-attachments/assets/bed0b37d-d417-43e3-b20c-cc3e88315bbf">
<img width="322" alt="Captura de ecrã 2024-09-20, às 15 55 20" src="https://github.com/user-attachments/assets/9741a3b1-aecb-4c44-9355-5af5bccd0f7b">

I get that my model is not of a good fit, but I would like to understand better the interpretation of the residuals vs. predicted (what are the red lines, the black points and the grey shading)

**Comment by melina-leite** [comment]
Hi @MatildeCorreia17,
the plot to the right side is produced by the `plotResiduals` function. The help page of the function can help you interpret the results:

- Given that you have a very large dataset (>10000), instead of plotting all the data points, the function produces a smoothed color density representation of the scatterplot (see the help of the function `smoothScatter` in the package graphics). So, the more gray the more data points.

- The red dotted line, in your case, is a smooth spline (the default for datasets larger than 2000). It shows a deviation from the expected straight line around 0.5. 

It is probable that you have heteroscedasticity in your data, i.e. the dispersion changes with the predicted mean (indicated by the non-straight line for the spline and the white triangle area in the bottom left of the plot), you could address it with the dispersion argument in glmmTMB. 

Or it could be also the case that the Gamma distribution (with the link function you are using) is not the best distribution for your data.

Best,
Melina

**Comment by melina-leite** [comment]
Hi @MatildeCorreia17, did you solve your problem?
If so, I'm going to close the issue. :)

**Comment by MatildeCorreia17** [comment]
Yes, thank you!

Melina de Souza Leite ***@***.***> escreveu (quinta,
10/10/2024 à(s) 10:40):
