### ISSUE TITLE
Issue Interpreting residual patterns for a GLMER Binomial Logistic Regression Model 

### ISSUE THREAD

**Issue by coanv** [florianhartig/DHARMa#448]
Hi,

I am using a multi-level "within/between" or "hybrid" model specification to predict the likelihood of holding credit card debt (0 = no, 1 = yes) as a function of caregiving status (0 = not caregiver, 1 = caregiver) and a slew of control predictors. I have 6 waves of panel data where observations are nested in people (grouping variable: HHIDPN). I've determined that a hybrid model specification  (using group centered means and deviations for time variant predictors) is a better fit than a mixed model specification via an LR test using anova(). My hybrid model currently has multiple random effects (Random Intercept on Person ID (HHIDPN) and Random Slope on Year2) 

This is the model specification I'm attempting to run diagnostics on using DHARMA
`mHF2<- glmer(haveccd ~ gender  + coll + race + year2 + care2a.m + rmstatc.m+ employ.m+homeown.m + 
               selfhlth.m +scale(rageyb.m) +hhhres.m +loghinc_real.m+
               care2a.d+rmstatc.d+employ.d+homeown.d+selfhlth.d+scale(rageyb.d)+hhhres.d+
               loghinc_real.d+(1|HHIDPN)+(year2-1|HHIDPN) ,data=ch1anly, family=binomial, 
               control=glmerControl(optimizer="nlminbwrap"))`
 
Following the instructions outlined [here](https://cran.r-project.org/web/packages/DHARMa/vignettes/DHARMa.html) I have run the following code 
`simulationOutput <- simulateResiduals(fittedModel = mHF2) plot(simulationOutput, asFactor = TRUE)`

Which gives me these plots 
![image](https://github.com/user-attachments/assets/bf168389-f227-4924-bc59-375d2ee8b8bb)

**My understanding is I should be seeing a boxplot for the graph on the right given that I specified asFactor = TRUE and I'm not sure why that is not happening.** 

I then tried to test for possible zero-inflation given that the majority of my sample does not have credit card debt and is therefore coded as 0. 

`testZeroInflation(simulationOutput)`

And I get this output

![image](https://github.com/user-attachments/assets/009580ca-133a-43e5-b790-a81f7e7a7e17)

<img width="694" alt="image" src="https://github.com/user-attachments/assets/19beca4b-6f7a-48c7-9215-222ed8b04edd">

I think this is telling me that I do have zero inflation and need to adjust for that. But I'm not sure if I'm understanding the output correctly and if I am, what my next step should be. I'm hoping someone can help me understand why I am not getting a boxplot for my residuals despite specifying asFactor = TRUE, and also help me understand what this output means and what my next steps should be in trying to find the best fitting model.

**Comment by florianhartig** [comment]
Hi,

1. Regarding asFactor: as Melina said, asFactor = T doesn't make sense if you don't have a single categorical predictor or at least very few predictors. However, the interaction of this option with smoothScatter is a bit odd - @melina-leite should we fix this so that asFactor also works for n>10.000?

2. Regarding the plots: @coanv, the more sensible plot option in your case is to set quantreg = T, which forces the calculation of the quantile regression lines. This will take a while, but will make your plot much better interpretable. I would recommend that you do this for res ~ fitted and res ~ predictors

3. Regarding the zeros: what the test shows you is not zero-inflation, but you have too few zeros. The tests also show some deviations from the distribution and the dispersion. It is uncommon (actually not really possible) to have these problems in 0/1 data, and effects are (in their size) really small, so I believe that this (i.e. the significant p-values) is created by the strong REs in your model in combination with your large sample size. Try to re-run the simulation with option re.form = NULL in the simulate residuals. This should create conditional simulations. If tests are fine then, there's nothing to worry.

Best
F

**Comment by melina-leite** [comment]
Hi @coanv, did you solve your problem?
If so, I'll close this issue, if not, please reopen it and we keep discussing.
Best,
Melina
