### ISSUE TITLE
Different model diagnostic on MacOs and Windows 11

### ISSUE THREAD

**Issue by DanieleCarlesso-Research** [florianhartig/DHARMa#455]
Hi, 

I work both at home using MacOS and at the office using Windows 11. All my code is on cloud so that I can work on it everywhere I am. Today I was running a GLMM model that I adjusted while working on Windows, and noticed a drastic difference in the diagnostic reported on my Mac compared to that reported on my windows machine. I am now unsure of which diagnostics are more accurate. 

On Mac:
![image](https://github.com/user-attachments/assets/12a362a1-3ab7-4677-8c5e-0effd8a2b950)

On Windows:
![b60ceeb0-6d55-4575-adee-70bea665997e](https://github.com/user-attachments/assets/bed9818e-0bdb-4dac-af9c-05c5db5fe17c)

As you can see, Windows return somewhat acceptable diagnostics, but Mac returns a terrible fit. The model is fit using glmer, Gamma family and sqrt link.

**Comment by melina-leite** [comment]
Hi @DanieleCarlesso-Research,
Indeed, it seems to be a very different result, but I have no idea why it works differently. In principle, it shouldn't be different.
Could you send the code and data that we could test (here or by email)? It doesn't need to be all the dataset or code, but an example that is producing the differences.

**Comment by florianhartig** [comment]
Hi @DanieleCarlesso-Research,

what Melina said - it seems very unlikely to me that you would get these results on different machines - maybe check again that this is not due to the fact that you still had a different result in memory on one of these machines, but if you can indeed reproduce these different plots with a minimal script on two different OS, please send us this example because this should not happen of course.

Best
F

**Comment by melina-leite** [comment]
Hi @DanieleCarlesso-Research, did you solve your problem? 
If not, feel free to reopen the issue and send us a reproducible code example so that we can work to find the problem and solution.
