### ISSUE TITLE
Tweedie distributions are handled as continuous, but can have point mass at zero = discrete

### ISSUE THREAD

**Issue by aosmith16** [florianhartig/DHARMa#66]
Now that DHARMa supports glmmTMB models (which is awesome), we can get simulated residuals for Tweedie models.  

I've had some unusual-looking scaled residual plots for such models, and after poking around a bit using simulated data I believe it's because the Tweedie distribution is bounded to be 0 or positive.  Other distributions, like the beta distribution, may have similar issues.  If I'm reading things correctly, random noise from a uniform distribution is added to avoid this problem for integer-valued (bounded) distributions when calculating the scaled residuals.

Here is an example to illustrate what I'm seeing.

``` r
library(glmmTMB) # v. 0.2.1.0
library(DHARMa) # v. 0.1.6.5

# Simulate Tweedie data
set.seed(16)
dat = data.frame( y = tweedie::rtweedie(1000, mu = 2, phi = 2, p = 1.5),
                    x = rnorm(1000) )

# Fit a model with single, unrelated explanatory variable
fit1 = glmmTMB(y ~ x, data = dat,
               family = tweedie)

# Look at simulated residuals
simres = simulateResiduals(fit1)
# It doesn't look like things fit quite right
plot(simres)
```

![](https://i.imgur.com/QNdAI26.png)

``` r

# Code to calculate scaled residuals in simulateResiduals()
# out$scaledResiduals[i] <- ecdf(out$simulatedResponse[i, ])(out$observedResponse[i])

# Simulate 100 response variables from model
sims = simulate(fit1, nsim = 100)

# Loop through and do the calculation manually
scaledres = sapply(1:nrow(sims), 
                   function(x) ecdf(sims[x,])(model.frame(fit1)[x, 1]),
                   simplify = TRUE)

# The resulting distribution clearly doesn't
    # appear to be uniform
gap::qqunif(scaledres, logscale = FALSE)
```

![](https://i.imgur.com/2gfuvWK.png)

``` r

# Code for integer responses in simulateResiduals avoids this problem
# out$scaledResiduals[i] <- ecdf(out$refittedResiduals[i, ] + runif(1000, -0.5, 0.5))(out$fittedResiduals[i] + runif(1, -0.5, 0.5))

scaledres2 = sapply(1:nrow(sims), 
                    function(x) ecdf(sims[x,] + runif(1000, -.5, .5))(model.frame(fit1)[x, 1] + runif(1, -0.5, 0.5)))

# Now things appear to reasonably come from a uniform distribution
gap::qqunif(scaledres2, logscale = FALSE)
```

![](https://i.imgur.com/F1bA5SC.png)

Created on 2018-05-25 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by florianhartig** [comment]
Hi,

many thanks for reporting this, this is indeed an issue, but I think 

- it's specific to Tweedie
- it's not specific to glmmTMB

The issue seems to be that the Tweedie can have point mass at zero, and it does in the parameterization that you have here. That means that there are many exact zeros in the data / simulated values, and for this DHARMa can't test if they are smaller / larger than simulated, thus the pattern in the residuals.

One could say that for some parameterizations, the Tweedie is kind of "semi-discrete".

I'm not sure if there are other distributions that have this property. I don't think Beta is an issue here. I'm also not sure if it is useful to always switch the Tweedie to discrete, as we have probably higher power without the added noise.

My suggested solution is to add a check in the residuals to see if the simulated data has non-unique values ... if it does, I switch the distribution to discrete, even if it's formally a continuous distribution.
