### ISSUE TITLE
Feature suggestions -- refer simulated data to reference data

### ISSUE THREAD

**Issue by jhmaindonald** [florianhartig/DHARMa#71]
It would be good to be able to use plotResiduals() to obtain plots for data simulated from the model, as in Section 2 (page 2) in the document attached to issue #70.  Also Figure 2 in the same document (pages 7 and 8) illustrates the usefulness, for diagnostic purposes, of plots that show the intra-class correlation estimates.

**Comment by florianhartig** [comment]
Hi John, I'm not 100% sure if I understand what you want - could you explain in a bit more detail?

The simulated data is of course stored in the DHARMa object, so you can extract it and plot it in any way desired. I'm not sure how sensible it would be to make plots, because the nature of the plots would probably depend a lot on the data type. 

Moreover, it seems in Fig. 2, you plot the estimates, not the simulated data?

**Comment by jhmaindonald** [comment]
Hi Florian,
I am after a straightforward way to get plots in the style of the figures on pages 3 and 4 — 
my approach is surely unnecessarily roundabout.  I have as excuse that the output list
elements from simulateResiduals() are not at this point individually  documented.

Figure 2 takes up a different theme.  They do plot estimates.  My point is that they
serve useful diagnostic (as well as other) purposes.  Possibly, such plots would be
more in place in glmmTMB.
Regards,
John Maindonald.

**Comment by florianhartig** [comment]
Hi John,

1. About this first point (plots) - so if I understand you correctly, what you want is plots in the style of the standard plotResiduals(), which, however, don't display the quantile residuals, but instead the simulated distribution vs. observed data? I guess that would be possible, but often such plots would be difficult to read, because the question is how to scale the x axis. Also, with n>50, this probably gets very hard to read. Here a try, where I plot the simulated distributions, ordered after predictions. The line are are predicted values, points are the observed data. Is that what you're after? 

```
testData = createData(sampleSize = 50, overdispersion = 0.5, family = poisson())
fittedModel <- glmer(observedResponse ~ Environment1 + (1|group), 
                     family = "poisson", data = testData,
                     control=glmerControl(optCtrl=list(maxfun=20000) ))

simulationOutput <- simulateResiduals(fittedModel = fittedModel)
library(vioplot)
predicted = simulationOutput$fittedPredictedResponse
ord = order(predicted)
df = data.frame(t(simulationOutput$simulatedResponse[ord,]))
do.call(vioplot,c(unname(df),col='lightgrey',drawRect=FALSE,names=list(names(df))))
lines(predicted[ord])
points(simulationOutput$observedResponse[ord], pch = 15, col = "red")
```

![image](https://user-images.githubusercontent.com/5457753/41155995-627d454c-6b20-11e8-8432-3a905ab40b8d.png)

 
2. "It occurs to me that you might provide an argument to `plotResiduals()` that is for residuals for one (or more?) of simulated sets of values, rather than for the residuals for the model." -> again, not 100% sure what you mean by "sets of values", but note that since DHARMa 0.2.0, which was just pushed to CRAN, there is a grouping option. See ?recalculateResiduals. This could of course be mixed with the plots above

```
# grouping per random effect group works as above
simulationOutput = recalculateResiduals(simulationOutput, group = testData$group)
plot(simulationOutput, quantreg = FALSE)
```

3. About the fitted values - there are of course many options to create them. If you simulate in DHARMa with refit = T, I also record the fitted fixed effects. You could for example calculate a parametric bootstrap from that. However, I have so far not implemented any analysis of these values, as I wanted to keep DHARMa a residual package, not a general GLMM analysis package. However, I see that there could be a value in doing more with this. Will think about it

**Comment by jhmaindonald** [comment]
Hi Florian,

> On 8/06/2018, at 23:37, Florian Hartig <notifications@github.com> wrote:
> 
> Hi John,
> 
> About this first point (plots) - so if I understand you correctly, what you want is plots in the style of the standard plotResiduals(), which, however, don't display the quantile residuals, but instead the simulated distribution vs. observed data? I guess that would be possible, but often such plots would be difficult to read, because the question is how to scale the x axis. Also, with n>50, this probably gets very hard to read. Here a try, where I plot the simulated distributions, ordered after predictions. The line are are predicted values, points are the observed data. Is that what you're after?
> testData = createData(sampleSize = 50, overdispersion = 0.5, family = poisson())
> fittedModel <- glmer(observedResponse ~ Environment1 + (1|group), 
>                      family = "poisson", data = testData,
>                      control=glmerControl(optCtrl=list(maxfun=20000) ))
> 
> simulationOutput <- simulateResiduals(fittedModel = fittedModel)
> library(vioplot)
> predicted = simulationOutput$fittedPredictedResponse
> ord = order(predicted)
> df = data.frame(t(simulationOutput$simulatedResponse[ord,]))
> do.call(vioplot,c(unname(df),col='lightgrey',drawRect=FALSE,names=list(names(df))))
> lines(predicted[ord])
> points(simulationOutput$observedResponse[ord], pch = 15, col = "red")
>  <https://user-images.githubusercontent.com/5457753/41155995-627d454c-6b20-11e8-8432-3a905ab40b8d.png>
What I have suggested is simpler than that.  I want exactly the same plots as for the observed 
data, but for a few sets of simulations [as given by simulate(), but one might as well just randomly
sample from the simulations that generated the reference distribution that is stored in the 
simulatedResponse list element in the output from simulateResiduals()].   The following takes just
one such simulation set, and scales it:

scaledSim <- function(simRef, nScale=1){
nObs <- simRef$nObs
nSim <- simRef$nSim
scaledRes <- matrix(0,nrow=nObs,ncol=nScale)
nSelect <- sample(nSim, size=nScale)
sampResponse <- simRef$simulatedResponse[ ,nSelect, drop=FALSE]
for(i in 1:nObs)scaledRes[i,] <- ecdf(simRef$simulatedResponse[i,
] + runif(simRef$nSim, -0.5, 0.5))(sampResponse[i,] + runif(nScale, -0.5, 0.5))
scaledRes
}

The output then replaces the scaled residuals from the fitted model, to give
exactly the same style of plot as before.  If a quantile curve goes 30 degrees
uphill for one such set of simulated values, and 30 degrees downhill in
another, then that gives a sense that anything within that range for the observed
data is pretty much consistent with the model.  It is a rough check, for sure, but
better than just eyeballing the output from plotResiduals() without any such
guide as to what might count as ‘close enough’ to a 25% or 50% or 75% 
horizontal quantile line.  The output that I attached gave examples.
Regards,
John Maindonald.

**Comment by florianhartig** [comment]
I am just reviewing old issues, and realised that I never responded to this, for which I'm sorry.

I understand the motivation for this, but think parts of this is reduced with the qgam switch in the 0.3 dev version, which provides a better overview for the user about which deviations are significant. 

There is still the issue of the randomization for discrete distributions. However, I think this is covered in https://github.com/florianhartig/DHARMa/issues/38 - I will therefore close this issue.

John, feel free to reopen if you think I'm missing something.
