### ISSUE TITLE
Diagonal residual line when using glmmTMB

### ISSUE THREAD

**Issue by ThomYorke7** [florianhartig/DHARMa#78]
Hi,

I'm currently working on a model that, unfortunately, I can't reproduce. I have a count type dependent variable, several count type independent variables, and thousands of observations taken from three subjects. 
The model I'm trying to fit is structured in the following way: model.1<-glmmTMB(dep.var. ~ ind.var1 + ind.var2 + ind.var3 + (1|Subjects/Observations), family = "nbinom2").
When I try to observe the residual plot with Dharma, this is the result:
![rplot](https://user-images.githubusercontent.com/41207866/42805622-9c932f12-89ac-11e8-9d14-9260a34bcd3a.png)
As it can be seen, there is a rather perfectly diagonal line in the graph on the right that I can't explain. When I fit the same formula with glmer.nb, I receive a totally different output (not diagonal, but not acceptable either). I have read issues #16 and #43  as I suppose they are related to this one. I have also thought that overdispersion may be the cause, but it should be accounted by the negative binomial family. Unfortunately, my inexperience in this field is stopping me from understanding many of the solutions proposed.

**Comment by florianhartig** [comment]
Hi @ThomYorke7 ,

sorry for the late reply - as you have realized, this could be created by #16 and #43 (actually, I find that likely), but it could also be another problem.

If you want to be sure, you could calculate unconditional model predictions by hand (by calculating exp [ sum(fitted values * predictors ] )) and plot the residuals vs. fitted plot by hand. If the pattern disappears, it was caused by the random effects.

I have asked the developers of glmmTMB to provide unconditional predictions, so that I hope that this problem can soon be solved. 

Best,
F
