### ISSUE TITLE
Warning from simulateResiduals when using DHARMa with lme4 glmer gamma family

### ISSUE THREAD

**Issue by Canderson156** [florianhartig/DHARMa#8]
Hi Florian,

Here is a reproducible example to show you the errors I've been getting when I try to use simulationOutput with a gamma glmm. Perhaps it is something specific to my models, but I'm getting the same error message from several different models. 

“Warning message:
In rgamma(nsim * length(ftd), shape = shape, rate = shape/ftd) :
NAs produced”

pop <- as.character(c("BF", "BF", "BF", "BF", "BF", "BF", "BF", "BF", "BF", "BF", "BF", "BF", "BF", "BF", "BF", "BF", "BF", "BF", "BF", "BF", "BF", "MA", "MA",
                      "MA", "MA", "MA", "MA", "MA", "MA", "MA", "MA", "MA", "MA", "MA", "MA", "MA", "NU", "NU", "NU", "NU", "NU", "NU", "NU", "NU", "NU", "SA",
                      "SA", "SA", "SA", "SA", "SA", "SA", "SA", "SA", "SA", "SA", "SA", "SA", "SA", "SA", "SA", "SA", "SA", "SA", "SA", "SA", "SA", "SA", "SA",
                      "SA", "SA", "SA", "SA", "SA"))
  
season <- as.character(c( "fall",   "spring", "fall",   "spring", "fall",   "spring", "fall",   "spring", "fall",   "spring", "fall",   "fall",   "spring", "fall",   "fall",   "spring", "fall",  
                          "spring", "spring", "fall",   "spring", "fall",   "spring", "fall",   "spring", "fall",   "spring", "fall",   "spring", "spring", "fall",   "spring", "spring", "fall",  
                          "spring", "spring", "fall",   "fall",   "fall",   "fall",   "fall",   "fall",   "fall",   "spring", "fall",   "fall",   "fall",   "spring", "fall",   "spring", "fall",  
                          "spring", "spring", "fall",   "fall",   "spring", "fall",   "spring", "spring", "fall",   "fall",   "fall",   "fall",   "spring", "fall",   "fall",   "spring", "spring",
                          "fall",   "fall",   "spring", "fall",   "fall",   "spring"))
  
  
id <- "2 2 4 4 7 7 9 9 10 10 84367 84367 84367 84368 84368 84368 84368 84368 84368 84369 84369 33073 33073 33073 33073 33073 33073 33073 33073 33073 80149 80149 80149 80150 80150 80150 57140 57141 126674 126677 126678 126680 137152 137152 137157 115925 115925 115925 115925 115925 115925 115925 115925 115926 115926 115926 115926 115926 115926 115927 115928 115929 115929 115929 115930 115930 115930 115930 115931 115931 115931 115932 115932 115932"
id <- strsplit(id, " ")
id <- as.numeric(unlist(id))

  
distance <-  "0.2970136 0.2813103 0.2409127 0.2461686 0.3392629 0.3246902 0.2938654 0.4403401 0.3935010 0.8161045 0.4622339 0.5448272 0.4347536 0.3623991 0.5014513 
0.3961407 0.4285523 0.5033465 0.3668231 0.4008644 0.3642039 0.5428035 0.6348236 0.5461090 0.5763835 0.4907923 0.4349144 0.4891743 0.6423068 0.4663140 
0.5226629 0.4855906 0.5868346 0.6429156 0.6363822 0.7002516 2.8778679 1.9055360 3.5048864 2.0234082 1.9940036 2.4991125 2.0742525 2.4859194 2.2326559 
0.5232152 0.4835573 0.4421921 0.6048358 1.0315084 0.4935351 0.5886613 0.4821023 0.9571798 0.5721407 0.5219413 0.4243556 0.6960064 0.4713459 0.6254402 
0.4887114 1.0324105 0.5536996 0.5539310 0.9808605 0.4164348 0.4658780 0.4707927 0.3722258 0.3805717 0.4608752 0.5829011 0.5095774 0.4262177"
distance <- strsplit(distance, " ")
distance <- as.numeric(unlist(distance))

distdata <- data.frame(pop = pop, season = season, id = id, distance = distance)

dist.glmm <- glmer(distance ~ pop * season + (1|id), 
                   data=distdata, family = Gamma, control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))

simulationOutput <- simulateResiduals(fittedModel = dist.glmm)

plotSimulatedResiduals(simulationOutput = simulationOutput)

**Comment by florianhartig** [comment]
Hi Christine,

quick summary: I think these residuals are for real, and Gamma isn't a good fit for this data. 

Details: there are 2 independent issues: 

1. The warning is created because the standard setting in DHARMa is to re-simulate the random effects. This can in some cases produce negative values on the linear predictor, which then produces NAs with the inverse link that is the default for Gamma. 

Solutions are either to not re-simulate the random effects (i.e. calculate residuals conditional on the fitted random effects),

```{r}
simulationOutput <- simulateResiduals(fittedModel = dist.glmm, use.u = T)
```
or to choose a link that allows negative values

```{r}
dist.glmm <- glmer(distance ~ pop * season + (1|id), data= distdata, family = Gamma(link = "log"))
```
Changing the link is a big step, so I guess one would usually choose option 1, although the fact that NAs occur does show that the data is not 100% in line with the model assumptions. If you get lots of NAs, I would think about whether a normally distributed random effect as in lme4 is still suitable for your data, or whether you should either transform the data, or move towards gamma-distributed random effects in another software (e.g. JAGS). 

2. The second issue is about the residuals. They look indeed underdispersed. This has nothing to do with the warning. My feeling is that this is actually correct, i.e. that the Gamma doesn't fit so well to the data and thus underdispersion occurs. I have played around a bit with the data, see here https://github.com/florianhartig/DHARMa/blob/master/Code/Examples/GammaProblems.md

**Comment by Canderson156** [comment]
Thanks for explaining, that makes a lot of sense. I suspected the residual plot was correct, but I wasn't sure due to the warnings.

**Comment by florianhartig** [comment]
Glad this was helpful. I'm closing this.
