### ISSUE TITLE
Help for plotResiduals is incorrect

### ISSUE THREAD

**Issue by mdwhitby** [florianhartig/DHARMa#94]
The helpfile for plotResiduals says the default is quantreg=NULL which would produce quantile regression lines. However from the examples it appears that quantreg=T should be the specification for conducting quantile regression. The default appears to be a spline (quantreg= F ?).

**Comment by florianhartig** [comment]
Hi Michael, 

thanks for the feedback!

NULL is neither T nor F. If you read on in the help, it says under quantreg that the behaviour depends on the number of data points:

`whether to perform a quantile regression on 0.25, 0.5, 0.75 on the residuals. If F, a spline will be created instead. Default NULL chooses T for nObs < 2000, and F otherwise.`

**Comment by florianhartig** [comment]
Sorry, I just noted that this may actually not be the case in your version, as this is related to https://github.com/florianhartig/DHARMa/issues/75 and I'm not sure if that change is already on CRAN.

So, apologies, you might have another message, but in the development version, this is fixed.
